### ISSUE TITLE
Missing link to poster

### ISSUE THREAD

**Issue by ChristophePhillips** [hMRI-group/hMRI-toolbox-docs#6]
On this line, 
https://github.com/hMRI-group/hMRI-toolbox-docs/blame/f30b784b72a5e3ed193329bcef6cc3c06581c6a5/docs/information.md#L56
the link to a poster (which one? ISMRM or OHBM?) is missing.

**Comment by halirutan** [comment]
I fixed the links (taken from hmri.info), but I think this section could use a rework. What I imagined was something like a "How to cite the hMRI Toolbox" section where this information would fit perfectly.

Also, this section would be a good place to add information about "logo and artwork" if someone wants to use it. We could link to the downloadable images there no matter if they are stored in the docs repository or the toolbox repository.
Additionally, people would find the information about the logos either by looking on the website or by googling it (because I'm pretty sure it will be the first hit).

**Comment by halirutan** [comment]
Also, see this PR #7

**Comment by ChristophePhillips** [comment]
Hi @halirutan 

Yesterday evening I was quickly going through the web pages and the "source code". Then I wanted to check how "easy" it would be to comment content, bring up issues, etc. but also to fix these. Looks like it's working smoothly thanks to GitHub (and you!). Thanks.

And yes, I would rather have a dedicated page with the citation and logo, at least with links to the latter. 😄 
Now checking PR #7.

**Comment by halirutan** [comment]
Fixed
